### ISSUE TITLE
Reactions are not getting through

### ISSUE THREAD

**Issue by AlexPewMaster** [ajkessel/reacjibot#4]
Hi, I wanted to set this plugin up as a starboard. Whenever people react to a message with a star (⭐), the bot should repost it in the starboard room. However, the bot isn't doing anything. When the message was reacted to with a star, it didn't repost it. The Maubot logs don't contain anything related to reacji except the initialization message. It says that it's mapping ⭐ with my room (formatted as "!room_id:homeserver"). One thing that's really strange: Whenever I react to a message with any other emoji, the logs report "checking for encryption on !room_id:homeserver". What's going on?

**Comment by ajkessel** [comment]
Sounds like a good use case.

Do you have `debug` set to `true` and `insecure` set to `true`? If you have some encrypted rooms and some unencrypted rooms, you can configure it to allow, or disallow, cross-posting from encrypted to unencrypted. Are your relevant rooms encrypted, unencrypted, or both? Does the bot respond to `!reacji help`, assuming you haven't changed the default bot command names?

Also, this is probably obvious, but is the bot a member of both the source and destination rooms?

**Comment by AlexPewMaster** [comment]
Hi, thanks for your quick response!
- Yes, I've set both `debug` and `insecure` to `true`.
- The bot is responding to `!reacji help`.
- The bot is a member of both rooms that I'm testing in.

**Comment by ajkessel** [comment]
I did some quick checking and for some reason mapping ⭐ from the command-line interface (i.e. `!reacji map ⭐ #room:domain.tld`) doesn't work, but mapping it from the config file (e.g. in the Maubot config console) works fine. I can't think of why that one emoji would behave differently than the others, but perhaps you can test my hypothesis on your end and at least confirm we're seeing the same behavior. Were you doing the initial mapping with `!reacji` rather than in Maubot console?

Updated: actually I spoke too soon. I'm not able to even create the mapping from `!reacji` but can from the console; however, the mapping still doesn't work. Maybe something with the Unicode for the star--will investigate.

**Comment by AlexPewMaster** [comment]
No, I did not use the `!reacji map` command. I configured it in the config using the Maubot web interface. Weirdly enough, choosing another emoji seems to fix the issue! I've now configured the reaction to be a skull emoji (💀) to trigger the starboard. Why is this happening?

**Comment by ajkessel** [comment]
Try the new release, let me know if that fixes it.

**Comment by AlexPewMaster** [comment]
You didn't attach a .mbp file to the release.

**Comment by ajkessel** [comment]
Oops!

![image](https://github.com/ajkessel/reacjibot/assets/3332524/f6b5c481-7c36-4874-80df-cbfca3f86a35)

Fixed now.

**Comment by AlexPewMaster** [comment]
I can confirm that this issue is now fixed. Thank you so much!
